{
 "title": "Overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "CBS_ID",
    "label": "Partners",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Active CloudWatch Alarms",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "region": "ca-central-1" }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Workload Counts by Partner (2.x)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expression": "fields CbsSensorId as CbsId\n| filter strcontains(\"$CBS_ID\", CbsId)\n| stats count() by CbsId, Workload\n| sort by Workload",
     "logGroups": [
      {
       "accountId": "${account_id}",
       "arn": "arn:aws:logs:ca-central-1:${account_id}:log-group:/aws/lambda/CBS-TransportLambda-${env}-ca-central-1:*",
       "name": "/aws/lambda/CBS-TransportLambda-${env}-ca-central-1"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [
      "CbsId",
      "Workload"
     ]
    }
   ]
  },
  {
   "title": "Workload Counts by Partner Routed from 1.x",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expression": "filter level = 'INFO'\n|filter strcontains(\"$CBS_ID\", CbsId)\n| stats count() by CbsId, Workload\n| sort by Workload",
     "logGroups": [
      {
       "accountId": "${account_id}",
       "arn": "arn:aws:logs:ca-central-1:${account_id}:log-group:/aws/lambda/CBS-SQSRouterLambda-${env}-ca-central-1:*",
       "name": "/aws/lambda/CBS-SQSRouterLambda-${env}-ca-central-1"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [
      "CbsId",
      "Workload"
     ]
    }
   ]
  },
  {
   "title": "CloudTrail Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expression": "fields Workload = \"cloudtrailLogs\" as cloudtrail, CbsSensorId as CbsId\n| filter strcontains(\"$CBS_ID\", CbsId)\n| stats sum(cloudtrail) as CloudTrailLogs by bin($__interval), CbsId",
     "logGroups": [
      {
       "accountId": "${account_id}",
       "arn": "arn:aws:logs:ca-central-1:${account_id}:log-group:/aws/lambda/CBS-TransportLambda-${env}-ca-central-1:*",
       "name": "/aws/lambda/CBS-TransportLambda-${env}-ca-central-1"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [
      "bin($__interval)",
      "CbsId"
     ]
    },
    {
     "expression": "fields Workload = \"cloudtrailLogs\" as cloudtrail\n| filter strcontains(\"$CBS_ID\", CbsId)\n| stats sum(cloudtrail) as CloudTrailLogs by bin($__interval), CbsId",
     "logGroups": [
      {
       "accountId": "${account_id}",
       "arn": "arn:aws:logs:ca-central-1:${account_id}:log-group:/aws/lambda/CBS-SQSRouterLambda-${env}-ca-central-1:*",
       "name": "/aws/lambda/CBS-SQSRouterLambda-${env}-ca-central-1"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [
      "bin($__interval)",
      "CbsId"
     ]
    }
   ]
  },
  {
   "title": "CloudWatch Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expression": "fields strcontains(Workload, \"cloudwatch\") as cloudwatch, CbsSensorId as CbsId\n| filter strcontains(\"$CBS_ID\", CbsId)\n| stats sum(cloudwatch) as CloudWatchLogs by bin($__interval), CbsId",
     "logGroups": [
      {
       "accountId": "${account_id}",
       "arn": "arn:aws:logs:ca-central-1:${account_id}:log-group:/aws/lambda/CBS-TransportLambda-${env}-ca-central-1:*",
       "name": "/aws/lambda/CBS-TransportLambda-${env}-ca-central-1"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [
      "bin($__interval)",
      "CbsId"
     ]
    },
    {
     "expression": "fields strcontains(Workload, \"cloudwatch\") as cloudwatch\n| filter strcontains(\"$CBS_ID\", CbsId)\n| stats sum(cloudwatch) as CloudWatchLogs by bin($__interval), CbsId",
     "logGroups": [
      {
       "accountId": "${account_id}",
       "arn": "arn:aws:logs:ca-central-1:${account_id}:log-group:/aws/lambda/CBS-SQSRouterLambda-${env}-ca-central-1:*",
       "name": "/aws/lambda/CBS-SQSRouterLambda-${env}-ca-central-1"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [
      "bin($__interval)",
      "CbsId"
     ]
    }
   ]
  },
  {
   "title": "VPC Flow Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expression": "fields strcontains(Workload, \"vpcFlowLogs\") as vpcflowlogs, CbsSensorId as CbsId\n| filter strcontains(\"$CBS_ID\", CbsId)\n| stats sum(vpcflowlogs) as VPCFlowLogs by bin($__interval), CbsId",
     "logGroups": [
      {
       "accountId": "${account_id}",
       "arn": "arn:aws:logs:ca-central-1:${account_id}:log-group:/aws/lambda/CBS-TransportLambda-${env}-ca-central-1:*",
       "name": "/aws/lambda/CBS-TransportLambda-${env}-ca-central-1"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [
      "bin($__interval)",
      "CbsId"
     ]
    },
    {
     "expression": "fields strcontains(Workload, \"vpcFlowLogs\") as vpcflowlogs\n| filter strcontains(\"$CBS_ID\", CbsId)\n| stats sum(vpcflowlogs) as VPCFlowLogs by bin($__interval), CbsId",
     "logGroups": [
      {
       "accountId": "${account_id}",
       "arn": "arn:aws:logs:ca-central-1:${account_id}:log-group:/aws/lambda/CBS-SQSRouterLambda-${env}-ca-central-1:*",
       "name": "/aws/lambda/CBS-SQSRouterLambda-${env}-ca-central-1"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [
      "bin($__interval)",
      "CbsId"
     ]
    }
   ]
  },
  {
   "title": "ELB Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expression": "fields Workload = \"elbLogsV2\" as elblogs, CbsSensorId as CbsId\n| filter strcontains(\"$CBS_ID\", CbsId)\n| stats sum(elblogs) as ELBLogs by bin($__interval), CbsId",
     "logGroups": [
      {
       "accountId": "${account_id}",
       "arn": "arn:aws:logs:ca-central-1:${account_id}:log-group:/aws/lambda/CBS-TransportLambda-${env}-ca-central-1:*",
       "name": "/aws/lambda/CBS-TransportLambda-${env}-ca-central-1"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [
      "bin($__interval)",
      "CbsId"
     ]
    },
    {
     "expression": "fields Workload = \"elbLogsV2\" as elblogs\n| filter strcontains(\"$CBS_ID\", CbsId)\n| stats sum(elblogs) as ELBLogs by bin($__interval), CbsId",
     "logGroups": [
      {
       "accountId": "${account_id}",
       "arn": "arn:aws:logs:ca-central-1:${account_id}:log-group:/aws/lambda/CBS-SQSRouterLambda-${env}-ca-central-1:*",
       "name": "/aws/lambda/CBS-SQSRouterLambda-${env}-ca-central-1"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [
      "bin($__interval)",
      "CbsId"
     ]
    }
   ]
  },
  {
   "title": "Accelerator Metadata",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expression": "fields Workload like /Metadata$/ as isMetadata, CbsSensorId as CbsId\n| filter strcontains(\"$CBS_ID\", CbsId)\n| stats sum(isMetadata) as Metadata by bin(24h), CbsId",
     "logGroups": [
      {
       "accountId": "${account_id}",
       "arn": "arn:aws:logs:ca-central-1:${account_id}:log-group:/aws/lambda/CBS-TransportLambda-${env}-ca-central-1:*",
       "name": "/aws/lambda/CBS-TransportLambda-${env}-ca-central-1"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [
      "bin(24h)",
      "CbsId"
     ]
    },
    {
     "expression": "fields Workload like /Metadata$/ as isMetadata\n| filter strcontains(\"$CBS_ID\", CbsId)\n| stats sum(isMetadata) as Metadata by bin(24h), CbsId",
     "logGroups": [
      {
       "accountId": "${account_id}",
       "arn": "arn:aws:logs:ca-central-1:${account_id}:log-group:/aws/lambda/CBS-SQSRouterLambda-${env}-ca-central-1:*",
       "name": "/aws/lambda/CBS-SQSRouterLambda-${env}-ca-central-1"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [
      "bin(24h)",
      "CbsId"
     ]
    }
   ]
  },
  { "title": "Transport Lambda", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Transport Lambda Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expression": "fields @message\r\n| filter strcontains(\"$CBS_ID\", CbsSensorId)",
     "logGroups": [
      {
       "accountId": "${account_id}",
       "arn": "arn:aws:logs:ca-central-1:${account_id}:log-group:/aws/lambda/CBS-TransportLambda-${env}-ca-central-1:*",
       "name": "/aws/lambda/CBS-TransportLambda-${env}-ca-central-1"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Transport Lambda Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "expression": "fields @message\n| filter level not like /INFO|WARNING/\n| filter @message not like /START|END|REPORT/",
     "logGroups": [
      {
       "accountId": "${account_id}",
       "arn": "arn:aws:logs:ca-central-1:${account_id}:log-group:/aws/lambda/CBS-TransportLambda-${env}-ca-central-1:*",
       "name": "/aws/lambda/CBS-TransportLambda-${env}-ca-central-1"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Transport Lambda Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": {
      "FunctionName": "CBS-TransportLambda-${env}-ca-central-1"
     },
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Transport Lambda Invocations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": {
      "FunctionName": "CBS-TransportLambda-${env}-ca-central-1"
     },
     "expression": "filter strcontains(\"$CBS_ID\", CbsSensorId)\n| stats count(@message) as Invocations by bin(5m)",
     "logGroups": [
      {
       "accountId": "${account_id}",
       "arn": "arn:aws:logs:ca-central-1:${account_id}:log-group:/aws/lambda/CBS-TransportLambda-${env}-ca-central-1:*",
       "name": "/aws/lambda/CBS-TransportLambda-${env}-ca-central-1"
      }
     ],
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Sum",
     "statsGroups": [ "bin(5m)" ]
    }
   ]
  },
  {
   "title": "Data Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dimensions": {
      "FunctionName": "CBS-TransportLambda-${env}-ca-central-1"
     },
     "expression": "filter strcontains(\"$CBS_ID\", CbsSensorId)\n| stats sum(Size) as Data by bin(5m)",
     "logGroups": [
      {
       "accountId": "${account_id}",
       "arn": "arn:aws:logs:ca-central-1:${account_id}:log-group:/aws/lambda/CBS-TransportLambda-${env}-ca-central-1:*",
       "name": "/aws/lambda/CBS-TransportLambda-${env}-ca-central-1"
      }
     ],
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Sum",
     "statsGroups": [ "bin(5m)" ]
    }
   ]
  },
  { "title": "SQS Router Lambda", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "SQS Router Lambda Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 83 },
   "targets": [
    {
     "expression": "fields @message\r\n| filter strcontains(\"$CBS_ID\", CbsId)",
     "logGroups": [
      {
       "accountId": "${account_id}",
       "arn": "arn:aws:logs:ca-central-1:${account_id}:log-group:/aws/lambda/CBS-SQSRouterLambda-${env}-ca-central-1:*",
       "name": "/aws/lambda/CBS-SQSRouterLambda-${env}-ca-central-1"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "SQS Router Lambda Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 91 },
   "targets": [
    {
     "expression": "fields @message\n| filter level not like /INFO|WARNING/\n| filter @message not like /START|END|REPORT/",
     "logGroups": [
      {
       "accountId": "${account_id}",
       "arn": "arn:aws:logs:ca-central-1:${account_id}:log-group:/aws/lambda/CBS-SQSRouterLambda-${env}-ca-central-1:*",
       "name": "/aws/lambda/CBS-SQSRouterLambda-${env}-ca-central-1"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "SQS Router Lambda Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": {
      "FunctionName": "CBS-SQSRouterLambda-${env}-ca-central-1"
     },
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "SQS Router Lambda Invocations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": {
      "FunctionName": "CBS-SQSRouterLambda-${env}-ca-central-1"
     },
     "expression": "filter strcontains(\"$CBS_ID\", CbsId)\n| stats count(@message) as Invocations by bin(5m)",
     "logGroups": [
      {
       "accountId": "${account_id}",
       "arn": "arn:aws:logs:ca-central-1:${account_id}:log-group:/aws/lambda/CBS-SQSRouterLambda-${env}-ca-central-1:*",
       "name": "/aws/lambda/CBS-SQSRouterLambda-${env}-ca-central-1"
      }
     ],
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Sum",
     "statsGroups": [ "bin(5m)" ]
    }
   ]
  },
  { "title": "SQS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 } },
  {
   "title": "Messages in Transit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 108 },
   "targets": [
    {
     "dimensions": { "QueueName": "CBS-SQS-${env}-ca-central-1" },
     "metricName": "NumberOfMessagesSent",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "QueueName": "CBS-SQS-${env}-ca-central-1" },
     "metricName": "NumberOfMessagesReceived",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "QueueName": "CBS-SQS-${env}-ca-central-1" },
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Message Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dimensions": { "QueueName": "CBS-SQS-${env}-ca-central-1" },
     "metricName": "ApproximateAgeOfOldestMessage",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  }
 ]
}