[GLOBAL]
pants_version = "2.20.0"
backend_packages.add = [
  "pants.backend.python",
  "pants.backend.experimental.python.lint.ruff.check",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.autoflake",
]
pants_ignore = [
  "!.cicd/**",
  "!**/remote_config.json",
]

[source]
root_patterns = [
  "/",
  "/cbs/",
  "/.github/scripts/",
]

[python]
interpreter_constraints = [">=3.9"]

[python-infer]
imports = false

[ruff]
config_discovery = true
